---
microstrain_inertial_driver_node:
  ros__parameters:
    device_setup: True
    imu_enable: True
    # gnss1_enable: false
    # gnss2_enable: false
    # publish_imu: true
    debug: True
    # port: /dev/ttyACM0
    # baudrate: 115200
    tf_mode: 0
    # ntrip_interface_enable: false
    low_pass_filter_config: False
    raw_file_enable: False
    timestamp_source: 0



