---
microstrain_inertial_driver_node:
  ros__parameters:
    device_setup: true
    imu_enable: true
    gnss1_enable: false
    gnss2_enable: false
    filter_enable: false
    filter_manual_config: false
    filter_manual: false
    filter_frequency: 0
    publish_filter: false
    publish_imu: true
    # debug: true
    port: /dev/ttyACM0
    baudrate: 115200
    tf_mode: 0
    ntrip_interface_enable: false
    low_pass_filter_config: false
