---
microstrain_inertial_driver_node:
  ros__parameters:
    device_setup: true
    imu_enable: true
    publish_imu: true
    gnss1_enable: false
    gnss2_enable: false
    debug: true
    port: /dev/ttyACM0
    baudrate: 115200
    tf_mode: 0
    low_pass_filter_config: false
    raw_file_enable: false
    timestamp_source: 0
    filter_manual_config: true
    filter_auto_heading_alignment_selector: 5
    filter_init_position: [0.0, 0.0, 0.0]
    filter_init_velocity: [0.0, 0.0, 0.0]
    filter_init_attitude: [4.712, 0.0, 1.5707]
